version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: orquestrador_db
    restart: always
    environment:
      MYSQL_DATABASE: orquestrador
      MYSQL_USER: orquestrador
      MYSQL_PASSWORD: orquestrador
      MYSQL_ROOT_PASSWORD: root_password_super_secreta
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"   # se quiser acessar MySQL pela sua máquina: localhost:3307
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: orquestrador_web
    restart: always
    env_file:
      - .env          # o .env que ajustamos ali em cima
    depends_on:
      - db
    ports:
      - "8001:8000"
    volumes:
      # pra desenvolvimento, mantém código sincronizado
      - .:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000

      "

volumes:
  db_data:
