version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: orquestrador_db
    restart: always
    environment:
      MYSQL_DATABASE: orquestrador
      MYSQL_USER: orquestrador
      MYSQL_PASSWORD: orquestrador
      MYSQL_ROOT_PASSWORD: root_password_super_secreta
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"   # acessar MySQL pela sua máquina: localhost:3307
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: orquestrador_web
    restart: always
    env_file:
      - .env          # o .env que ajustamos
    depends_on:
      - db
    ports:
      - "8001:8001"   # acessar Django em http://localhost:8001
    volumes:
      # pra desenvolvimento, mantém código sincronizado
      - .:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py ensure_default_superuser &&
        python manage.py runserver 0.0.0.0:8000
      "

  scheduler:
    build: .
    container_name: orquestrador_scheduler
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py automation_scheduler --interval 60
      "

volumes:
  db_data:
